# Generated by Django 4.1.6 on 2023-02-11 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('doc_url', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('bio', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('uid', models.CharField(max_length=25)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LearnedTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccapi.tech')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(null=True)),
                ('learned_tech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapi.learnedtech')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccapi.user')),
            ],
        ),
    ]
