# Generated by Django 4.1.6 on 2023-03-17 00:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('parent_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnedTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('doc_url', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('bio', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=150)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccapi.goal')),
                ('learned_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapi.learnedtech')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='learnedtech',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccapi.tech'),
        ),
        migrations.AddField(
            model_name='learnedtech',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapi.user'),
        ),
        migrations.AddField(
            model_name='goal',
            name='learned_tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapi.learnedtech'),
        ),
        migrations.AddField(
            model_name='goal',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapi.user'),
        ),
    ]
