# Generated by Django 4.1.6 on 2023-02-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
