# Generated by Django 4.1.6 on 2023-03-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='uid',
        ),
    ]
