# Generated by Django 4.1.7 on 2023-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
