# Generated by Django 4.1.7 on 2023-06-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0002_rename_tech_resource_learned_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='title', max_length=25),
            preserve_default=False,
        ),
    ]
