# Generated by Django 4.1.6 on 2023-02-12 01:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0002_alter_tech_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=150)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ccapi.goal')),
                ('learned_tech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapi.learnedtech')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccapi.user')),
            ],
        ),
    ]
