# Generated by Django 4.1.7 on 2023-06-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0003_alter_goal_title_alter_topic_title_alter_user_uid'),
        ('ccapi', '0003_resource_last_updated_resource_title'),
    ]

    operations = [
    ]
