# Generated by Django 4.1.6 on 2023-02-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0003_message_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='learned_tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapi.learnedtech'),
        ),
    ]
